//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bus_Ticket_Sales_Automation
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adminler
    {
        public int adminId { get; set; }
        public string adminAd { get; set; }
        public string adminSoyad { get; set; }
        public string adminKullaniciAdi { get; set; }
        public string adminSifre { get; set; }
        public string adminEposta { get; set; }
    }
}
